<?php

declare(strict_types=1);

namespace App\Notifications;

use Illuminate\Auth\Notifications\ResetPassword;

/**
 * FirmOwnerInvitationNotification — the firm panel's own analogue of
 * ClientPortalResetPasswordNotification (see that class's own docblock
 * for why Laravel's default `ResetPassword` notification cannot be used
 * unmodified: it builds its link via `route('password.reset', ...)`, a
 * plain named route this app does not have — every panel is
 * Filament-scoped). Neither `FirmPanelProvider` nor `AdminPanelProvider`
 * had a working password-reset flow at all before this feature
 * (confirmed pre-existing gap, documented in FirmPanelProvider's own
 * updated docblock) — `->passwordReset()` is now enabled on the `firm`
 * panel specifically to give this notification's link somewhere real to
 * go.
 *
 * Used for both the brand-new owner's first-time password SETUP and any
 * later ordinary "forgot password" reset — Laravel's password-reset flow
 * does not distinguish the two, and neither does this notification;
 * `User::sendPasswordResetNotification()` sends this for every reset,
 * matching ClientPortalUser's own identical, non-special-cased override.
 *
 * Only overrides `resetUrl()` — subject/body/`via()` are inherited
 * unchanged from Laravel's own notification. The token itself is never
 * touched here: it arrives already generated by the password broker
 * (Illuminate\Auth\Passwords\PasswordBroker), which stores only a
 * one-way hash of it (`Hash::make($token)`) — this class only builds a
 * URL string around the plaintext token for the ONE outbound email, and
 * never persists or logs it.
 */
class FirmOwnerInvitationNotification extends ResetPassword
{
    protected function resetUrl($notifiable)
    {
        return url(route('filament.firm.auth.password-reset.reset', [
            'email' => $notifiable->getEmailForPasswordReset(),
            'token' => $this->token,
        ], false));
    }
}
