<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Financial Evidence Report</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #1a1a1a; }
        h1 { font-size: 18px; margin-bottom: 4px; }
        h2 { font-size: 14px; margin-top: 18px; margin-bottom: 6px; border-bottom: 1px solid #ccc; padding-bottom: 2px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        td, th { padding: 4px 6px; text-align: left; vertical-align: top; }
        .label { width: 220px; font-weight: bold; color: #444; }
        .limitations { padding: 8px; background: #f5f5f5; border: 1px solid #ddd; }
        .footer { margin-top: 24px; font-size: 10px; color: #777; }
    </style>
</head>
<body>
    <h1>Financial Evidence Report</h1>
    <p>Matter: {{ $matter->uuid ?? $matter->id }} — Report version {{ $snapshot->report_version }}</p>

    <h2>Source and Authorization</h2>
    <table>
        <tr><td class="label">Source product</td><td>{{ $snapshot->source_product }}</td></tr>
        <tr><td class="label">Authorized date range</td><td>{{ $snapshot->date_range_start?->toDateString() ?? '—' }} to {{ $snapshot->date_range_end?->toDateString() ?? '—' }}</td></tr>
        <tr><td class="label">Provider retrieval time</td><td>{{ $snapshot->provider_retrieved_at?->toDayDateTimeString() ?? '—' }}</td></tr>
        <tr><td class="label">Included record count</td><td>{{ count($snapshot->retrieved_record_refs_json ?? []) }}</td></tr>
    </table>

    <h2>Report Metadata</h2>
    <table>
        <tr><td class="label">Generated at</td><td>{{ $snapshot->created_at?->toDayDateTimeString() }}</td></tr>
        <tr><td class="label">Checksum</td><td>{{ $snapshot->checksum ?? 'None' }} ({{ $snapshot->checksum_source ?? 'n/a' }})</td></tr>
        <tr><td class="label">Redacted request reference</td><td>{{ $snapshot->redacted_request_reference ?? '—' }}</td></tr>
        <tr><td class="label">Consent reference</td><td>{{ $snapshot->consent_id ?? '—' }}</td></tr>
        <tr><td class="label">Reviewer status</td><td>{{ $reviewerStatus }}</td></tr>
    </table>

    <h2>Limitations</h2>
    <div class="limitations">{{ $snapshot->limitations_text }}</div>

    <div class="footer">
        Generated by FirmsVault Financial Evidence Workspace. This document is a fixed-in-time export of a
        previously generated evidence snapshot; it does not reflect data received after the snapshot was created.
    </div>
</body>
</html>
